"""empty message

Revision ID: a7d924adb268
Revises: 0e5279ed109c
Create Date: 2019-07-20 12:16:13.801185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d924adb268'
down_revision = '0e5279ed109c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assigneeId', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('ownerId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['assigneeId'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['ownerId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'ownerId')
    op.drop_column('task', 'assigneeId')
    # ### end Alembic commands ###
